text2pdf: some refactoring

diff --git a/text2pdf b/text2pdf
--- a/text2pdf
+++ b/text2pdf
@@ -1,30 +1,35 @@
 #!/bin/bash
 # Converts ASCII text files to PDf
+set -o errexit
+set -o nounset
 
+A2PS_ARGS="--tabsize=4 --portrait --highlight-level=heavy --prologue=color --columns=1 --font-size=11 --media=A4 --chars-per-line=80 --line-numbers=1"
+PS2PDF_ARGS="-sPAPERSIZE=a4 -dOptimize=true -dEmbedAllFonts=true"
+		
 
 # check for commandline arguments
-if [ "$#" = 0 ] ; then
-	echo "no target file specified."
-	echo "usage: text2pdf file"
+if [ "$#" = 0 ]
+then
+	echo "No input files specified."
+	echo "usage: text2pdf input_file..."
 fi
 
 
 # do conversion
-for ARG in "$@" ; do
-
-
-	if [ -f $ARG ] ; then
-	
-		a2ps --tabsize=4 --portrait --highlight-level=heavy --prologue=color --columns=1 --font-size=11 --media=A4 --chars-per-line=80 --line-numbers=1 --output=- $ARG \
-		| ps2pdf -sPAPERSIZE=a4 -dOptimize=true -dEmbedAllFonts=true - $ARG.pdf
-	
-		if [ -f "$ARG.pdf" ] ; then
-			echo "$ARG converted. Saved to $ARG.pdf"
-		else
-			echo "error: conversion mied have been aborted, new file does not exist"
-		fi
-	
+for FILE in "$@"
+do
+if [ -f "$FILE" ]
+	then
+	    if [ -r "${FILE}" ]
+	    then
+		    a2ps ${A2PS_ARGS} --output=- "$FILE" | ps2pdf ${PS2PDF_ARGS} - "${FILE}.pdf"
+		    echo "${FILE} converted. Saved to ${FILE}.pdf"
+	    else
+	        echo "${FILE} skipped: Cannot read file ${FILE}"
+	        exit -1
+        fi
 	else
-		echo "$ARG skipped: file does not exist"
+		echo "${FILE} skipped: Not a regular file"
 	fi
+
 done
