nearly rewrite text2ps text2pdf

diff --git a/text2pdf b/text2pdf
--- a/text2pdf
+++ b/text2pdf
@@ -1,35 +1,48 @@
 #!/bin/bash
 # Converts ASCII text files to PDf
+
 set -o errexit
-set -o nounset
+# debugging
+#set -x
 
-A2PS_ARGS="--tabsize=4 --portrait --highlight-level=heavy --prologue=color --columns=1 --font-size=11 --media=A4 --chars-per-line=80 --line-numbers=1"
 PS2PDF_ARGS="-sPAPERSIZE=a4 -dOptimize=true -dEmbedAllFonts=true"
-		
+INPUT_FILE="$1"
+OUTPUT_FILE="$2"
 
-# check for commandline arguments
-if [ "$#" = 0 ]
+EXIT_BADARGS=2
+
+
+function print_usage()
+{
+	echo "Invalid number of arguments."
+	echo "Usage: text2pdf input_file [ output_file | - ]"
+}
+
+
+# wrong number of args?
+if [ "$#" = 0 ] || [ "$#" -ge 3 ]
 then
-	echo "No input files specified."
-	echo "usage: text2pdf input_file..."
+    print_usage
+    exit ${EXIT_BADARGS}
+else
+    # check input file
+    if [ ! -f "${INPUT_FILE}" ]
+    then
+        echo "${INPUT_FILE}: No regular file. Exit."
+        exit ${EXIT_BADARGS}
+    else
+        if [ ! -r "${INPUT_FILE}" ]
+        then
+            echo "${INPUT_FILE}: No read permission. Exit"
+        fi
+    fi
+    
+    if [ "$#" = 1 ]
+    then
+        OUTPUT_FILE="${INPUT_FILE}.pdf"
+    fi
 fi
 
+text2ps "${INPUT_FILE}" - | ps2pdf ${PS2PDF_ARGS} -sOutputFile="${OUTPUT_FILE}" -
 
-# do conversion
-for FILE in "$@"
-do
-if [ -f "$FILE" ]
-	then
-	    if [ -r "${FILE}" ]
-	    then
-		    a2ps ${A2PS_ARGS} --output=- "$FILE" | ps2pdf ${PS2PDF_ARGS} - "${FILE}.pdf"
-		    echo "${FILE} converted. Saved to ${FILE}.pdf"
-	    else
-	        echo "${FILE} skipped: Cannot read file ${FILE}"
-	        exit -1
-        fi
-	else
-		echo "${FILE} skipped: Not a regular file"
-	fi
-
-done
+exit $?
diff --git a/text2ps b/text2ps
--- a/text2ps
+++ b/text2ps
@@ -1,26 +1,47 @@
 #!/bin/bash
 # Converts ASCII text files to PostScript
 
+set -o errexit
+# debugging
+#set -x
 
-# check for commandline arguments
-if [ "$#" = 0 ] ; then
-	echo "no target file specified."
-	echo "usage: text2ps file"
+A2PS_ARGS="--tabsize=4 --portrait --highlight-level=heavy --prologue=color --columns=1 --font-size=11 --media=A4 --chars-per-line=80 --line-numbers=1 --quiet"
+INPUT_FILE="$1"
+OUTPUT_FILE="$2"
+
+EXIT_BADARGS=2
+
+
+function print_usage()
+{
+	echo "Invalid number of arguments."
+	echo "Usage: text2ps input_file [ output_file | - ]"
+}
+
+# wrong number of args?
+if [ "$#" = 0 ] || [ "$#" -ge 3 ]
+then
+    print_usage
+    exit ${EXIT_BADARGS}
+else
+    # check input file
+    if [ ! -f "${INPUT_FILE}" ]
+    then
+        echo "${INPUT_FILE}: No regular file. Exit."
+        exit ${EXIT_BADARGS}
+    else
+        if [ ! -r "${INPUT_FILE}" ]
+        then
+            echo "${INPUT_FILE}: No read permission. Exit"
+        fi
+    fi
+    
+    if [ "$#" = 1 ]
+    then
+        OUTPUT_FILE="${INPUT_FILE}.ps"
+    fi
 fi
 
+a2ps ${A2PS_ARGS} --output="${OUTPUT_FILE}" "${INPUT_FILE}"
 
-# do conversion
-for ARG in "$@" ; do
-
-	if [ -f $ARG ] ; then
-		a2ps --tabsize=4 --portrait --highlight-level=heavy --prologue=color --columns=1 --font-size=11 --media=A4 --chars-per-line=80 --line-numbers=1 --output="$ARG.ps" $ARG
-	
-		if [ -f "$ARG.ps" ] ; then
-			echo "$ARG converted. Saved to $ARG.ps"
-		else
-			echo "error: conversion mied have been aborted, new file does not exist"
-		fi
-	else
-		echo "$ARG skipped: file does not exist"
-	fi
-done
+exit $?
